abstract class AppStrings {
  static const String yourEmail = "Your Email",
      password = "Password",
      signIn = "Sign In",
      dontHaveAnAccount = "Don't have an account? ",
      register = "Register",
      fullName = "Full Name",
      phone = "Phone",
      signUp = "Sign Up",
      haveanaccount = "have an account? ",
      searchProduct = "Search Product",
      superFlashSale = "Super Flash Sale",
      categories = "Categories",
      viewall = "View all",
      accessories = "Accessories",
      clocks = "clocks",
      furniture = "Furniture",
      mostPopular = "Most Popular",
      seeMore = "See More",
      fSNikeAirMaxReact = "FS - Nike Air Max 270 React...",
      fSQUILTEDMAXICROS = "FS - QUILTED MAXI CROS...",
      aboutUs = "About Us",
      whoweare = "Who we are?",
      lorem =
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor...  ",
      readmore = "Read more",
      mostPopularForWoman = "Most Popular For Woman",
      mostPopularFormAN = "Most Popular For Man",
      hotDeals = "Hot Deals",
      nikeAirMaxReactENG = "Nike Air Max 270 React ENG",
      home = "Home",
      explore = "Explore",
      cart = "Cart",
      offer = "Offer",
      account = "Account";
}
